config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('room/<int:pk>', views.room, name='room'),
    path('create-room/', views.create_room, name='create-room'),
    path('update-room/<int:pk>', views.update_room, name='update-room'),
    path('delete-room/<int:pk>', views.delete_room, name='delete-room'),
]

home/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Topic(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name


class Room(models.Model):
	host = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)
	topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
	name = models.CharField(max_length=200)
	description = models.TextField(null=True, blank=True)
	# participants
	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-updated', '-created']

	def __str__(self):
		return self.name


class Message(models.Model):
	user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)
	room = models.ForeignKey(Room, on_delete=models.SET_NULL, null=True)
	body = models.TextField(max_length=300)
	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.body[0:50]

home/forms.py
from django.forms import ModelForm
from .models import Room


class RoomForm(ModelForm):
	class Meta:
		model = Room
		# fields = ('host', 'topic', 'name', 'description', 'updated', 'created') # participants
		# error_messages = {
		#
		# }
		fields = '__all__'

home/views.py
from django.shortcuts import render, redirect

from .models import Room
from .forms import RoomForm


def home(request):
	rooms = Room.objects.all()
	context = {'rooms': rooms}
	return render(request, 'home/home.html', context)


def room(request, pk):
	single_room = Room.objects.get(pk=pk)
	context = {'room': single_room}
	return render(request, 'home/room.html', context)


def create_room(request):
	form = RoomForm()

	if request.method == 'POST':
		form = RoomForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('home:home')

	context = {'form': form}
	return render(request, 'home/room_form.html', context)


def update_room(request, pk):
	edited_room = Room.objects.get(id=pk)
	form = RoomForm(instance=edited_room)

	if request.method == 'POST':
		form = RoomForm(request.POST, instance=edited_room)
		if form.is_valid():
			form.save()
			return redirect('home:home')

	context = {'form': form}
	return render(request, 'home/room_form.html', context)


def delete_room(request, pk):
	deleted_room = Room.objects.get(id=pk)

	if request.method == "POST":
		deleted_room.delete()
		return redirect('home:home')

	return render(request, 'home/delete.html', {'obj': deleted_room})

home/templates/home/delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" action="">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ obj }}"?</p>
        <a class="btn btn-dark" href="{{ request.META.HTTP_REFERER }}">Go back</a>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    {{ block.super }}
{% endblock %}

{% block scripts %}
    {{ block.super }}
{% endblock %}


{% block title %}
    - Home
{% endblock %}

{% block content %}
    <h2>Home</h2>
    {% for room in rooms %}
        <div>
            <a href="{% url 'home:update-room' room.id %}">Edit</a>
            <a href="{% url 'home:delete-room' room.id %}">Delete</a>
            <span>{{ room.topic.name }} - added by - {{ room.host.username }}</span>
            <h5>{{ room.id }} - <a href="{% url 'home:room' room.id   %}">{{ room.name }}</a></h5>

        </div>
    {% endfor %}
{% endblock %}

home/templates/home/room.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    {{ block.super }}
{% endblock %}

{% block scripts %}
    {{ block.super }}
{% endblock %}


{% block title %}
{#    - {{ room.name }}#}
{% endblock %}

{% block content %}
    <h2>You're  now in "{{ room.name }}" room.</h2>
    {% for room in rooms %}
        <div>

            <h5>{{ room.id }} - {{ room.name }}</h5>
        </div>
    {% endfor %}
{% endblock %}

home/templates/home/room_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{#{% load crispy_forms_tags %}#}

{% block content %}
    <div>
        <form method="POST" action="">
            {% csrf_token %}
            {{ form|crispy}}
            <input class="btn btn-dark" type="submit" value="Submit">

        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BeerBuddy {% block title %}{% endblock %}</title>

    {% block styles %}
        <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    {% endblock %}

    {% block scripts %}
        <script src="{% static 'scripts/bootstrap.min.js' %}" async defer></script>
    {% endblock %}

</head>
<body>

{% include 'partial/_navbar.html' %}

    <div class="container mt-3">
        <div class="row">
            <div class="col-8">
                {% block content %} {% endblock %}
            </div>
            <div class="col-4 mt-3">
                {% block aside %} {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

templates/partial/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:home' %}">
        <img src="{% static 'images/logo.svg' %}" alt="logo" class="logoimage m-lg-2">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Find your buddies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:create-room' %}">Create Room</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Your buddies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Your profile</a>
        </li>
      </ul>
    </div>
  </div>
</nav>